-- 1. EVERYTHING IS WRITE BUT CASE OF FONTS IS DIFFERENT. 
 SELECT LAST_NAME, JOB_ID, SALARY AS Sal FROM EMPLOYEE

-- 2. above qury is right
 SELECT EMPLOYEE_ID, LAST_NAME, SALARY*12 FROM EMPLOYEE

-- 3
sp_columns Employee

-- 4
select distinct JOB_ID from EMPLOYEE

-- 5
select 
	EMPLOYEE_ID , 
	LAST_NAME , 
	SALARY AS [OLD_SALARY] , 
	(SALARY*0.155 + SALARY) as [NEW_SALARY] , 
	((SALARY*0.155 + SALARY) - SALARY) as [INCREMENT]
from EMPLOYEE


-- 6 

-- BY DEPARTMENTNAME
select 
	d.DEPARTMENT_NAME ,
	MAX(salary) as MAX_Salary , 
	MIN(salary) as MIN_Salary ,
	AVG(salary) as AVG_Salary ,
	SUM(salary) as SUM_Salary
from  DEPARTMENTS d
INNER JOIN EMPLOYEE e
on e.DEPARTMENT_ID = d.DEPARTMENT_ID
group by d.DEPARTMENT_NAME


-- BY DEPARTMENTID
SELECT 
	DEPARTMENT_ID, 
	MAX(salary) AS MAX_Salary ,  
	MIN(salary) AS MIN_Salary , 
	AVG(salary) as AVG_Salary ,
	SUM(salary) as SUM_Salary
FROM EMPLOYEE
GROUP BY DEPARTMENT_ID



-- 7. 

-- list of all Manager
SELECT distinct CONCAT(e2.FIRST_NAME,' ',e2.LAST_NAME)  AS EMPLOYEE_NAME , e2.HIRE_DATE as Emp_HIRE_DATE , CONCAT(e1.FIRST_NAME,' ',e1.LAST_NAME) AS MANAGER_NAME , e1.HIRE_DATE  as MNG_HIRE_DATE FROM EMPLOYEE e1
inner join EMPLOYEE e2
on e1.EMPLOYEE_ID = e2.MANAGER_ID
where e2.HIRE_DATE < e1.HIRE_DATE



-- 8. 


SELECT e1.EMPLOYEE_ID as EMPLOYEE_1, e1.DEPARTMENT_ID AS 'DEPARTMENT OF EMPLOYEE 1' , e2.EMPLOYEE_ID  as EMPLOYEE_2 , e2.DEPARTMENT_ID AS 'DEPARTMENT OF EMPLOYEE 2' 
FROM EMPLOYEE e1 , EMPLOYEE e2
where e1.EMPLOYEE_ID != e2.EMPLOYEE_ID and e1.DEPARTMENT_ID = e2.DEPARTMENT_ID



-- 9 

SELECT MAX(SALARY) AS MAX_SALARY, MIN(SALARY) AS MIN_SALARY , SUM(SALARY) AS AVG_SALARY, AVG(SALARY) AS SUM_SALARY FROM EMPLOYEE

-- 10 
 -- employee having salary greater than max salary of depart 60
 -- MAX Salary of employee of department 60 = 9000
SELECT EMPLOYEE_ID , SALARY
FROM EMPLOYEE 
where SALARY > (SELECT MAX(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT_ID HAVING DEPARTMENT_ID=60)